### ISSUE TITLE
And ideas about make the app Material Design?

### ISSUE THREAD

**Issue by zwpaper** [GreenSkinMonster/hipda#2]
Hi, 
The UI of hipda has been a long time unchanged, Do you got any idea of making it Material Design, or improve the UI?
I found some libs might help, what's you idea?

[https://github.com/navasmdc/MaterialDesignLibrary]()
[https://github.com/rengwuxian/MaterialEditText]()
[https://github.com/makovkastar/FloatingActionButton]()
[https://github.com/Yalantis/Context-Menu.Android]()
[https://github.com/Yalantis/Side-Menu.Android]()

**Comment by GreenSkinMonster** [comment]
Will consider this later, after current version is stable enough.
