### ISSUE TITLE
Invalid package reference in library; not included in Android: java.nio.file. 

### ISSUE THREAD

**Issue by sunriseyuen** [GreenSkinMonster/hipda#3]
okio-1.7.0-SNAPSHOT.jar: Invalid package reference in library; not included in Android: java.nio.file. 

编译的时候出提示
在 配置文件 build.gradle 加入

  lintOptions {
        warning 'InvalidPackage'
    }

后可以成功编译。

**Comment by GreenSkinMonster** [comment]
这个文件在 hipda/libs 目录下面，我这编译是没有问题的。
你看下是否跟这个问题类似 https://github.com/square/okio/issues/58
