### ISSUE TITLE
能不能实现个标记帖子热度的功能

### ISSUE THREAD

**Issue by h2ero** [GreenSkinMonster/hipda#5]
![wx20170723-001327](https://user-images.githubusercontent.com/1262641/28492770-e2c2fd3c-6f3b-11e7-9501-33f50e7064d7.png)

网页的写的greasemonkey脚本实现的，使用不同颜色标记热度，
最近用你的Android版本没有这个功能感觉不方便，能否实现下？

**Comment by GreenSkinMonster** [comment]
感觉帖子列表显示这么大片颜色会有点乱，我还是倾向于简单一点。
